pluginManagement {
    repositories {
        maven { url 'https://mirrors.tencent.com/nexus/repository/maven-public/' }
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)
    repositories {
        maven { url 'https://mirrors.tencent.com/nexus/repository/maven-public/' }
        google()
        mavenCentral()
    }
}

rootProject.name = "PhotoTranslate"
include(":app")
